### ISSUE TITLE
MSAA issue with sprites and sprite batch

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#581]
Hi, 
MSAA feature in Xenko 2 has issue with sprites and sprite batch.

Testing example here: http://emptykeys.com/uploads/Xenko2IssueMSAA.zip

Without MSAA you will see yellow sprite and big white one. If you turn on MSAA they disappear.

**Comment by LautrecOfCarim** [comment]
Hi @EmptyKeys 

I just confirmed the issue and I added high priority on our internal tracker, hopefully should be fixed soon.

**Comment by LautrecOfCarim** [comment]
Thank you for the test example, we fixed it internally. Should be out with the next patch (2.0.2).

**Comment by EmptyKeys** [comment]
Tested in 2.0.2.1 and still not working correctly. Sprite looks weird and spritebatch not showing up at all. Was the fix part of latest version?
