### ISSUE TITLE
Error when starting new project. VS17 15.3 not supported?

### ISSUE THREAD

**Issue by asusralis** [SiliconStudio/paradox#617]
Error: An exception occurred while generating the template.. Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\Users\Kyle\Documents\Xenko Projects\MyGame2\MyGame2\MyGame2.Game\MyGame2.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at SiliconStudio.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 200
   at SiliconStudio.Assets.Package.FindAssetsInProject(String projectFullPath, String& nameSpace) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1380
   at SiliconStudio.Assets.Package.FindAssetsInProject(ICollection`1 list, Package package) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1407
   at SiliconStudio.Assets.Package.ListAssetFiles(ILogger log, Package package, Boolean listAssetsInMsbuild, Nullable`1 cancelToken) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1374
   at SiliconStudio.Assets.Package.LoadTemporaryAssets(ILogger log, List`1 assetFiles, Nullable`1 cancelToken, Boolean listAssetsInMsbuild, Func`2 filterFunc) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 967
   at SiliconStudio.Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.Generate(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\Templates\NewGameTemplateGenerator.cs:line 166
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\SessionTemplateGenerator.cs:line 41
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0() in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\TemplateGeneratorHelper.cs:line 56

I'm assuming it's because I'm on VS2017 15.3 and not 15.2. I had a similar problem with another tool chain. Yes, I do have MSBuild installed.

**Comment by FrogsAreGood** [comment]
I've been looking into game design for a little while now and have stumbled on this "gem" of an engine, I found and heard of this engine off a work colleague and thus installed all the needed visual-studio files in order to make the engine run and then proceeded to hit the install button on the launcher. And to my surprise, I got the exact same engine error that you seem to have gotten. My barbaric methods of swearing at my run-down PC in a fit of anger haven't worked. At all. Have you a solution?

Error Message Received:

Verbose: Loading Assets from Package [Xenko.xkpkg]
Error: Unexpected error while loading project [C:\Users\Max De Chastelain\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Game\ThirdPersonPlatformer.Game.csproj] or assembly reference []. Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\Users\Max De Chastelain\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Game\ThirdPersonPlatformer.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at SiliconStudio.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 200
   at SiliconStudio.Assets.VSProjectHelper.GetOrCompileProjectAssembly(String solutionFullPath, String fullProjectLocation, ILogger logger, String targets, Boolean autoCompileProject, Boolean forceNugetRestore, String configuration, String platform, Dictionary`2 extraProperties, Boolean onlyErrors, BuildRequestDataFlags flags) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 76
   at SiliconStudio.Assets.Package.LoadAssemblyReferencesForPackage(ILogger log, PackageLoadParameters loadParameters) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1146
Error: Error while pre-loading package [SiliconStudio.Assets.Package]. Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\Users\Max De Chastelain\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Game\ThirdPersonPlatformer.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at SiliconStudio.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 200
   at SiliconStudio.Assets.Package.FindAssetsInProject(String projectFullPath, String& nameSpace) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1380
   at SiliconStudio.Assets.Package.FindAssetsInProject(ICollection`1 list, Package package) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1407
   at SiliconStudio.Assets.Package.ListAssetFiles(ILogger log, Package package, Boolean listAssetsInMsbuild, Nullable`1 cancelToken) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1374
   at SiliconStudio.Assets.PackageSession.TryLoadAssets(PackageSession session, ILogger log, Package package, PackageLoadParameters loadParameters) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\PackageSession.cs:line 1019
Verbose: Compiling game assemblies...
Error: Unexpected error while loading project [C:\Users\Max De Chastelain\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Game\ThirdPersonPlatformer.Game.csproj] or assembly reference []. Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\Users\Max De Chastelain\Documents\Xenko Projects\ThirdPersonPlatformer\ThirdPersonPlatformer\ThirdPersonPlatformer.Game\ThirdPersonPlatformer.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at SiliconStudio.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 200
   at SiliconStudio.Assets.VSProjectHelper.GetOrCompileProjectAssembly(String solutionFullPath, String fullProjectLocation, ILogger logger, String targets, Boolean autoCompileProject, Boolean forceNugetRestore, String configuration, String platform, Dictionary`2 extraProperties, Boolean onlyErrors, BuildRequestDataFlags flags) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 76
   at SiliconStudio.Assets.Package.LoadAssemblyReferencesForPackage(ILogger log, PackageLoadParameters loadParameters) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1146
Verbose: Game assemblies compiled...
Error: Could not find game settings asset at location [GameSettings]
Verbose: Restoring NuGet packages...

Although not Identical, the Error seems to be very similar.

**Comment by Kryptos-FR** [comment]
It was announced on the forums (https://forums.xenko.com/t/dont-update-to-visual-studio-2017-15-3/1198) that Visual Studio 15.3 (more specifically MSBuild) has an issue that Microsoft is currently fixing (https://github.com/Microsoft/msbuild/issues/2369). Unfortunately it looks like Microsoft will not release the fix anytime soon so I'm currently working on a workaround.

**Comment by FrogsAreGood** [comment]
Erroneous bugs like these are typical from Microsoft, endless problems like this one have occurred with instances of VisualStudio. 

If this Error is not resolved soon: I may have to resort to the Unity3D engine for game design. 

But I will be happy to aid you in search of a solution, my experience is limited.

**Comment by Kryptos-FR** [comment]
Thanks. I have a fix that seems to be working. It is currently under testing and if everything goes well we can release it soon (in one or two days).

**Comment by Kryptos-FR** [comment]
Fixed in version 2.0.4.1

**Comment by matmuze** [comment]
Still having the same problem despite have updated to 2.0.4.1

**Comment by asusralis** [comment]
I can confirm that this was fixed for me in 2.0.4.1. 

@matmuze Are you sure you have the proper dependencies downloaded? Were you able to run Xenko before? This was my first time using Xenko, so maybe you have a different problem than me.

**Comment by Kryptos-FR** [comment]
@matmuze Can you describe exactly the issue you now have? Is it the same error message and/or call stack trace?
